name: Build and deploy notebooks

#  Only run this when the master branch changes
on: 
  workflow_dispatch:

permissions:
  pull-requests: write
  
jobs:
  validation:
   uses: therealzoidberg/notebook_ci_template/.github/workflows/ci_builder.yml@main
