on:
  workflow_call:
  
jobs:
  execute_notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        notebook: ${{ toJson(github.event.pull_request.changes) }}
    name:  Execute notebooks on PR
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Nav to notebook directory
        run: |
          cd "$(dirname "${{ matrix.notebook }}")"
      - name: Install dependencies
        run: |
          pip install pytest
          pip install nbval
          pip install nbconvert
          pip install bandit
          pip install -r requirements.txt
      - name: Execute notebook
        run: |
          jupyter nbconvert --execute --inplace "${{ matrix.notebook }}" -- output "${{matrix.notebook}}"
      - name: Push executed notebook to gh-storage
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-storage
          directory: output
          force: true

