on:
  workflow_call:
  
jobs:
  executed_changed_notebooks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    ## routine to gather only the changed notebook files and supply them to the matrix
    - name: changed-files
      id: get-changed-files
      uses: tj-actions/changed-files@v34
      with:
        separator: ","
        files: |
          **/*.ipynb
    ## convert the list of files to an array and push them into the matrix as a json object      
    - name: set-matrix
      id: set-matrix
      run: |
        IFS=',' read -r -a array <<< "${{steps.get-changed-files.outputs.all_changed_files}}"
        echo "{$array}"
        echo "matrix=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${array[@]}")" >> $GITHUB_OUTPUT
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        pytho-version: '3.8'
    - name: Nav to notebook directory
      run: |
        cd "$(dirname "${{ matrix.notebook }}")"
    
    - name: Install dependencies
      run: |
        pip install pytest
        pip install nbval
        pip install nbconvert
        pip install bandit
        pip install -r requirements.txt
        
    - name: Execute changed notebooks
      run: |
        jupyter nbconvert --execute --inplace "${{ matrix.notebook }}" -- output "${{matrix.notebook}}"
        
    
  validate_notebooks:
    needs: [executed_changed_notebooks]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        notebook: [$JUPYTER_NOTEBOOKS]
    steps:
    - name: Nav to notebook directory
      run: |
        cd "$(dirname "${{ matrix.notebook }}")"

    - name: Install dependencies
      run: |
        pip install pytest
        pip install nbval
        pip install nbconvert
        pip install bandit
        pip install -r requirements.txt
        
    - name: Validate notebooks
      run: |
        nbval "${{ matrix.notebook }}"
        
  push_notebooks:
    needs: [executed_changed_notebooks, validate_notebooks]
    runs-on: ubuntu-latest
    steps:
    - name: push notebooks
      run: |
        git checkout -b gh-storage
        git add $JUPYTER_NOTEBOOKS
        git commit -m "Add changed notebooks"
        git push origin gh-storage





