on:
  workflow_call:
  
jobs:
  executed_changed_notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        notebook: [$JUPYTER_NOTEBOOKS]
    steps:
    - name: Get list of changed files
      run: | 
        CHANGED_FILES=$(GIT DIFF --NAME-ONLY HEAD HEAD~1)
        ECHO "CHANGED FILES: $CHANGED_FILES"
        
    - name: Filter to include only Jupyter notebooks
      run: |
        JUPYTER_NOTEBOOKS=$(echo "$CHANGED_FILES" | grep "\.ipynb$")
        echo "Jupyter notebooks: $JUPYTER_NOTEBOOKS"
        
    - name: Nav to notebook directory
      run: |
        cd "$(dirname "${{ matrix.notebook }}")"
    
    - name: Install dependencies
      run: |
        pip install pytest
        pip install nbval
        pip install nbconvert
        pip install bandit
        pip install -r requirements.txt
        
    - name: Execute changed notebooks
      run: |
        jupyter nbconvert --execute --inplace "${{ matrix.notebook }}"
        
    
  validate_notebooks:
    needs: [executed_changed_notebooks]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        notebook: [$JUPYTER_NOTEBOOKS]
    steps:
    - name: Nav to notebook directory
      run: |
        cd "$(dirname "${{ matrix.notebook }}")"

    - name: Install dependencies
      run: |
        pip install pytest
        pip install nbval
        pip install nbconvert
        pip install bandit
        pip install -r requirements.txt
        
    - name: Validate notebooks
      run: |
        nbval "${{ matrix.notebook }}"
        
  push_notebooks:
    needs: [executed_changed_notebooks, validate_notebooks]
    runs-on: ubuntu-latest
    steps:
    - name: push notebooks
      run: |
        git checkout -b gh-storage
        git add $JUPYTER_NOTEBOOKS
        git commit -m "Add changed notebooks"
        git push origin gh-storage





